# Generated by Django 4.2.7 on 2024-03-05 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0025_bookings_refund_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='places',
            name='Type',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
